import { ListPage, Products } from "@/pageComponents/index/parent";
import axios from "axios";
import React from "react";
import type { Metadata } from "next";

const refetch = async () => {
  const { data } = await axios.get<Products>(
    "https://dummyjson.com/products?limit=10"
  );

  return data;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Home: React.FC = async () => {
  const data = await refetch();

  return <ListPage {...data} split={4} />;
};

export default Home;
