import { ListPage, Products } from "@/pageComponents/index/parent";
import axios from "axios";
import React from "react";
import type { Metadata } from "next";
import { PageProps } from "../../.next/types/app/page";

const refetch = async (params: { page: string }) => {
  const { page = 1 } = params;
  const per_page = 20;

  const { data } = await axios.get<Products>(`https://dummyjson.com/products`, {
    params: {
      skip: (Number(page) - 1) * per_page,
      limit: Number(page) * per_page,
    },
  });

  const endReached = false;
  console.log("data:", data);

  return { ...data, endReached };
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Home: React.FC = async (props: PageProps) => {
  const data = await refetch(props.searchParams);

  return <ListPage {...data} />;
};

export default Home;
